[tasks.watch]
command = "cargo"
args = ["leptos","watch"]

[tasks.dev]
run_task = {name = ["watch", "style"], parallel = true}

[tasks.style]
command = "npx"
args = ["tailwindcss","-i","style/tailwind.css","-o" ,"assets/tailwind.css","--watch"]

