---
managers:
  hosts:
    bootstrap:
      ansible_host: ec2-52-49-195-208.eu-west-1.compute.amazonaws.com
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ../modules/cluster/node_key_2
workers:
  hosts:
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ../modules/cluster/node_key_2
