---
- name: Docker Service
  hosts: managers[0]
  tasks:
    - name: Docker Swarm Service
      community.docker.docker_swarm_service:
        name: nginx
        image: nginx
        replicas: 1
        resolve_image: true # update based on digest (i.e even if latest)
        publish:
          - mode: host
            published_port: 80
            target_port: 80
        healthcheck:
          # Check if nginx server is healthy by curl'ing the server.
          # If this fails or timeouts, the healthcheck fails.
          test: ["CMD", "curl", "--fail", "http://nginx.host.com"]
          interval: 1m30s
          timeout: 10s
          retries: 3
          start_period: 30s
        update_config:
          parallelism: 2
          delay: 10s
          order: stop-first
          failure_action: rollback
        rollback_config:
          parallelism: 2
          delay: 10s
          order: stop-first
        reservations:
          cpus: 0.25
          memory: 20M
        limits:
          cpus: 0.50
          memory: 50M
