---
- name: Docker Service
  hosts: managers[0]
  tasks:
    - name: Docker Swarm Service
      community.docker.docker_swarm_service:
        name: dev-asm
        image: ghcr.io/apollo-xiv/dev-asm
        replicas: 1
        resolve_image: true # update based on digest (i.e even if latest)
        publish:
          - mode: ingress
            published_port: 80
            target_port: 80
        # healthcheck:
        #   # Check if ghcr.io/apollo-xiv/dev-asm server is healthy by curl'ing the server.
        #   # If this fails or timeouts, the healthcheck fails.
        #   test: ["CMD", "curl", "--fail", "]
        #   interval: 1m30s
        #   timeout: 10s
        #   retries: 3
        #   start_period: 30s
        update_config:
          parallelism: 2
          delay: 10s
          order: stop-first
          failure_action: rollback
        rollback_config:
          parallelism: 2
          delay: 10s
          order: stop-first
        reservations:
          cpus: 0.25
          memory: 20M
        limits:
          cpus: 0.50
          memory: 50M
        secrets:
          - secret_name: CLIENT_ID
          - secret_name: CLIENT_SECRET
          - secret_name: AUTH_SECRET
          - secret_name: DATABASE_URL
- name: Docker Secrets
  hosts: managers[0]
  tasks:
    - name: Secret - GITHUB_CLIENT_ID
      community.docker.docker_secret:
        name: CLIENT_ID
        data: "{{lookup('file', './github_client_id') | b64encode}}"
        data_is_b64: true
        state: present
    - name: Secret - GITHUB_CLIENT_SECRET
      community.docker.docker_secret:
        name: CLIENT_SECRET
        data: "{{lookup('file', './github_client_secret') | b64encode}}"
        data_is_b64: true
        state: present
    - name: Secret - AUTH_SECRET
      community.docker.docker_secret:
        name: AUTH_SECRET
        data: "{{lookup('file', './auth_secret') | b64encode}}"
        data_is_b64: true
        state: present
    - name: Secret - CX_STRING
      community.docker.docker_secret:
        name: DATABASE_URL
        data: "{{lookup('file', './cx_string') | b64encode}}"
        data_is_b64: true
        state: present
