name: Build Container Image
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-image:
    permissions: write-all
    name: build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: build image
      run: docker build -t ghcr.io/apollo-xiv/dev-asm . # docker build command goes here
    - name: push image
      run: docker push ghcr.io/apollo-xiv/dev-asm:latest
