name: Infrastructure

on:
  workflow_call:

jobs:
  deploy-infra:
    name: Deploy infra
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create tfvars
      run: echo '${{secrets.TFVARS}}' >> secrets.auto.tfvars
    - name: Terraform Init
      run: terraform init
    - name: Terraform Apply
      run: terraform apply --auto-approve
