
name: Dispatch Jobs on Push to Main

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

jobs:
  check-infrastructure-config:
    # terraform
    name: Check Infrastructure Configuration
    uses: ./.github/workflows/infrastructure.yml
    secrets: inherit
  run-playbooks:
    runs-on: ubuntu
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: add ssh key
      run: echo ${{secrets.SSH_PRIVATE_KEY}} > infra/node_key
    - name: update service
      # You may pin to the exact commit or the version.
    # uses: dawidd6/action-ansible-playbook@c97d71562fcba83cc1ea0602d5a77013427f7571
      uses: dawidd6/action-ansible-playbook@v2.8.0
      with:
        # Ansible playbook filepath
        playbook: ./service.yml
        # Ansible Galaxy requirements filepath
        #requirements:  optional
        # Root directory of Ansible project (defaults to current)
        directory: ./infra/playbooks
        # Ansible configuration file content (ansible.cfg)
        #configuration: # optional
        # Custom content to write into hosts
        #inventory: # optional
        # The password used for decrypting vaulted files
        #vault_password: # optional
        # Contents of SSH known_hosts file
        #known_hosts: # optional
        # Extra options that should be passed to ansible-playbook command
        #options: # optional
        # Set to "true" if root is required for running your playbook
        sudo: true # optional
        # Set to "true" if the Ansible output should not include colors (defaults to "false")
        #no_color: # optional
            
