
name: Dispatch Jobs on Push to Main

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

jobs:
  infra:
    # terraform
    name: Check Infrastructure Configuration
    uses: ./.github/workflows/infrastructure.yml
    secrets: inherit
    
  build-image:
    name: Build docker image
    uses: ./.github/workflows/container.yml
    secrets: inherit
    
  run-playbooks:
    name: Run Ansible Playbooks
    uses: ./.github/workflows/playbooks.yml
    needs: [build-image, infra]
    secrets: inherit          

  terraform-destroy:
    name: Destroy Infrastructure
    needs: [run-playbooks]
    runs-on: ubuntu-latest
    steps:
    - name: Sign in to AWS CLI
      run: |
        export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY}} \
        export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_KEY}} \
        export AWS_DEFAULT_REGION=eu-west-1
    - run: terraform init
    - run: terraform destroy --auto-approve
    
