
name: Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

jobs:
  infra:
    # terraform
    name: Check Infrastructure Configuration
    uses: ./.github/workflows/infrastructure.yml
    secrets: inherit
    
  build-image:
    name: Build docker image
    uses: ./.github/workflows/container.yml
    secrets: inherit
    
  run-playbooks:
    name: Run Ansible Playbooks
    uses: ./.github/workflows/playbooks.yml
    needs: [build-image, infra]
    secrets: inherit          

  # terraform-destroy:
  #   name: Destroy Infrastructure
  #   uses: ./.github/workflows/destroy.yml
  #   needs: [run-playbooks]
  #   secrets: inherit
    
