name: Run Anisble Playbooks
on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-playbooks:
    name: run playbooks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/playbooks
    steps:
    - uses: actions/checkout@v3
    - name: Setup Ansible
      run: |
        sudo apt install -y pipx
        pipx install --include-deps ansible
    - name: Use Node Key
      run: |
        echo "$(echo ${{secrets.NODE_KEY_64}} | base64 -d)" > ../modules/cluster/node_key && \
        chmod 600 ../modules/cluster/node_key
    - name: download inventory.yml
      uses: actions/download-artifact@v4
      with:
        name: inventory
        path: inventory.yml
    - name: test service
      run: ansible-playbook -i inventory.yml service.yml
