name: Run Anisble Playbooks
on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-playbooks:
    name: run playbooks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Ansible
      run: |
        sudo apt install -y pipx
        pipx install --include-deps ansible

    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: build image
      run: docker build # docker build command goes here
    - name: push image
      run: docker push ghcr.io/apollo-xiv/dev-asm:latest
