name: Run Anisble Playbooks
on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-playbooks:
    name: run playbooks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/playbooks
    steps:
    - uses: actions/checkout@v4
    - name: Use Node Key
      run: |
        echo "$(echo ${{secrets.NODE_KEY_64}} | base64 -d)" > ../modules/cluster/node_key && \
        chmod 600 ../modules/cluster/node_key
    - name: download inventory.yml
      uses: actions/download-artifact@v4
      with:
        name: inventory
        path: infra/playbooks
    - name: download cx_secret
      uses: actions/download-artifact@v4
      with:
        name: cx_string
        path: infra/playbooks
    - name: Create secret files
      run: |
          echo ${{secrets.AUTH_SECRET}} > ./auth_secret && \
          echo ${{secrets.CLIENT_ID}} > ./github_client_id && \
          echo ${{secrets.CLIENT_SECRET}} > ./github_client_secret
    - name: Deploy Service
      run: ansible-playbook -i inventory.yml service.yml
